name: bio-env
channels:
  - default
  - conda-forge
  - eoas_ubc
dependencies:
  - python==3.7.*
  - pip
  - git
  - pandas
  - matplotlib
  - seaborn 
  - scipy
  - xlrd=1.2.0
  - NetworkX
  - scikit-learn
  - tabulate 
  - openpyxl 
  - pip:
    - quantecon
    - jupyter-book>=0.7.0b
